"""
Convergence Plotter

Reads the convergence.jsonl file generated by `run_experiments.py`,
averages the convergence curves across all 50 runs for each function,
and generates standard semi-log convergence graphs.
"""

import os
import glob
import json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

RESULTS_DIR = os.path.dirname(__file__).replace("src", "results")
PLOTS_DIR = os.path.join(RESULTS_DIR, "plots")

if not os.path.exists(PLOTS_DIR):
    os.makedirs(PLOTS_DIR)

def find_latest_jsonl():
    """Find the most recent convergence JSONL in the results directory."""
    files = glob.glob(os.path.join(RESULTS_DIR, "convergence*.jsonl"))
    if not files:
        raise FileNotFoundError(f"No convergence data found in {RESULTS_DIR}. Please run run_experiments.py first.")
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]

def plot_convergence():
    json_path = find_latest_jsonl()
    print(f"Reading convergence data from: {json_path}")
    
    # Data is deeply nested: data[Suite][Function][Algo] = List of lists (one per run)
    data = {}
    
    with open(json_path, 'r') as f:
        for line in f:
            if not line.strip():
                continue
            record = json.loads(line)
            suite = record["Suite"]
            func = record["Function"]
            conv = record["Convergence"] # dict: algo -> list
            
            if suite not in data:
                data[suite] = {}
            if func not in data[suite]:
                data[suite][func] = {alg: [] for alg in conv.keys()}
                
            for alg, curve in conv.items():
                data[suite][func][alg].append(curve)

    print(f"Found {len(data)} suites. Generating plots...")

    # For each function, compute average curve and plot
    for suite, funcs in data.items():
        for func_name, alg_runs in funcs.items():
            plt.figure(figsize=(10, 6))
            
            # Use dynamic markers and lines
            markers = ['o', 'v', '^', '<', '>', 's', 'p', '*', 'h', 'H', 'D', 'd']
            idx = 0
            
            for alg, curves in alg_runs.items():
                # Some algorithms log every FES, some log every epoch.
                # To average them smoothly, we will just find the minimum length across the 50 runs,
                # truncate them to that length, and average.
                if not curves: continue
                
                min_len = min(len(c) for c in curves)
                truncated_curves = [c[:min_len] for c in curves]
                
                avg_curve = np.mean(truncated_curves, axis=0)
                
                # To avoid plotting 60000 points which is messy, we subsample for the plot marker.
                # Plot line normally, but put markers at spaced intervals.
                x = np.arange(len(avg_curve))
                
                markevery = max(1, len(x) // 10)
                
                # Highlight MPCOA line to be thicker/distinct
                lw = 3.0 if alg == "MPCOA" else 1.5
                alpha = 1.0 if alg in ["MPCOA", "PCOA"] else 0.7
                
                plt.plot(x, avg_curve, label=alg, linewidth=lw, alpha=alpha, 
                         marker=markers[idx % len(markers)], markevery=markevery, markersize=8)
                idx += 1
                
            plt.title(f"Convergence Graph: {suite.upper()} - {func_name}")
            plt.xlabel("Iterations / Evaluations")
            plt.ylabel("Best Fitness (Log Scale)")
            plt.yscale('log')
            plt.legend(loc='upper right', bbox_to_anchor=(1.25, 1))
            plt.grid(True, which="both", ls="--", alpha=0.5)
            plt.tight_layout()
            
            out_path = os.path.join(PLOTS_DIR, f"conv_{suite}_{func_name}.png")
            plt.savefig(out_path, dpi=300)
            plt.close()
            
            print(f"  Saved -> {os.path.basename(out_path)}")

    print(f"\nAll plots saved to: {PLOTS_DIR}")

if __name__ == "__main__":
    try:
        plot_convergence()
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f"Error: {e}")
